site_name: FujiNet VirtualMachine Help

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Getting Started: gettingstarted.md
  - Running Emulators: emulators.md
  - FujiNet Web UI: webui.md
  - Tips/Tricks: tips.md
  - Troubleshooting: troubleshooting.md
  - Building: building.md
